// Mock Data for Univibe Student Platform
import {
  Student,
  Announcement,
  Event,
  Registration,
  LeaderboardEntry,
  ShopItem,
  Transaction,
  Notification,
} from '@/types/student';

// Current Student
export const mockStudent: Student = {
  id: 'student-1',
  name: 'Alex Johnson',
  email: 'alex.johnson@university.edu',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  faculty: 'Computer Science',
  group: 'CS-2024-A',
  year: 2,
  coins: 2450,
  rank: 7,
  previousRank: 9,
  badges: [
    { id: 'badge-1', name: 'Early Bird', icon: '🌅', description: 'Registered for 5 events early', earnedAt: '2026-01-15T10:00:00Z' },
    { id: 'badge-2', name: 'Social Butterfly', icon: '🦋', description: 'Attended 10 social events', earnedAt: '2026-01-20T14:00:00Z' },
    { id: 'badge-3', name: 'Volunteer Hero', icon: '🦸', description: 'Completed 3 volunteer events', earnedAt: '2026-01-25T09:00:00Z' },
  ],
  createdAt: '2024-09-01T00:00:00Z',
};

// Announcements
export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Spring Semester Registration Open',
    content: 'Online registration for Spring 2026 semester is now open. Please register for your courses before the deadline on February 15th. Contact the registrar office if you need assistance.',
    category: 'academic',
    createdAt: '2026-02-05T08:00:00Z',
    author: 'Registrar Office',
    isPinned: true,
  },
  {
    id: 'ann-2',
    title: 'Campus Wi-Fi Maintenance',
    content: 'Scheduled maintenance on campus Wi-Fi networks this Saturday from 2 AM to 6 AM. Please save your work and plan accordingly.',
    category: 'general',
    createdAt: '2026-02-04T14:30:00Z',
    author: 'IT Department',
    isPinned: false,
  },
  {
    id: 'ann-3',
    title: 'Winter Sports Festival Starting Soon',
    content: 'Join us for the annual Winter Sports Festival from February 10-15. Register now to participate in various sports competitions.',
    category: 'event',
    createdAt: '2026-02-03T10:00:00Z',
    author: 'Sports Committee',
    isPinned: false,
  },
  {
    id: 'ann-4',
    title: 'Library Extended Hours During Exams',
    content: 'The main library will extend its hours during the exam period. New hours: 7 AM - 12 AM (midnight). Study rooms can be booked online.',
    category: 'general',
    createdAt: '2026-02-02T09:00:00Z',
    author: 'Library Services',
    isPinned: false,
  },
];

// Events
export const mockEvents: Event[] = [
  {
    id: 'event-1',
    title: 'Tech Innovation Workshop: AI & Machine Learning',
    description: 'Join us for an interactive workshop exploring the latest trends in AI and machine learning. Learn from industry experts and get hands-on experience with cutting-edge tools.',
    coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=200&fit=crop',
    date: '2026-02-10',
    startTime: '14:00',
    endTime: '17:00',
    location: 'Tech Hub, Building A, Room 301',
    organizer: 'Computer Science Department',
    capacity: 50,
    registeredCount: 42,
    registrationDeadline: '2026-02-08',
    category: 'workshop',
    tags: ['AI', 'Machine Learning', 'Technology'],
    coinReward: 100,
    badgeReward: 'Tech Explorer',
    status: 'open',
  },
  {
    id: 'event-2',
    title: 'Career Fair 2026',
    description: 'Connect with over 50 top employers looking for talented students. Bring your resume and dress professionally. Networking opportunities available.',
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=200&fit=crop',
    date: '2026-02-15',
    startTime: '10:00',
    endTime: '16:00',
    location: 'University Convention Center',
    organizer: 'Career Services',
    capacity: 500,
    registeredCount: 385,
    registrationDeadline: '2026-02-14',
    category: 'career',
    tags: ['Career', 'Networking', 'Jobs'],
    coinReward: 150,
    status: 'registered',
  },
  {
    id: 'event-3',
    title: 'Basketball Tournament Finals',
    description: 'Watch the finals of the inter-faculty basketball tournament. Cheer for your faculty team!',
    coverImage: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=200&fit=crop',
    date: '2026-02-12',
    startTime: '18:00',
    endTime: '21:00',
    location: 'Sports Complex, Main Court',
    organizer: 'Sports Committee',
    capacity: 200,
    registeredCount: 200,
    registrationDeadline: '2026-02-11',
    category: 'sports',
    tags: ['Basketball', 'Sports', 'Competition'],
    coinReward: 50,
    status: 'closed',
  },
  {
    id: 'event-4',
    title: 'Cultural Night: International Food Festival',
    description: 'Experience cuisines from around the world prepared by our international student community. Live music and cultural performances.',
    coverImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=200&fit=crop',
    date: '2026-02-20',
    startTime: '17:00',
    endTime: '22:00',
    location: 'Student Center Plaza',
    organizer: 'International Students Association',
    capacity: 300,
    registeredCount: 156,
    registrationDeadline: '2026-02-18',
    category: 'cultural',
    tags: ['Food', 'Culture', 'International'],
    coinReward: 75,
    status: 'open',
  },
  {
    id: 'event-5',
    title: 'Environmental Cleanup Day',
    description: 'Help beautify our campus and local community. Tools and supplies provided. Make a difference!',
    coverImage: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400&h=200&fit=crop',
    date: '2026-02-22',
    startTime: '09:00',
    endTime: '13:00',
    location: 'Meet at Main Gate',
    organizer: 'Environmental Club',
    capacity: 100,
    registeredCount: 45,
    registrationDeadline: '2026-02-21',
    category: 'volunteer',
    tags: ['Environment', 'Community', 'Volunteer'],
    coinReward: 200,
    badgeReward: 'Green Champion',
    status: 'open',
  },
  {
    id: 'event-6',
    title: 'Public Speaking Masterclass',
    description: 'Learn the art of public speaking from a professional coach. Improve your presentation skills for academic and professional success.',
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=200&fit=crop',
    date: '2026-02-25',
    startTime: '15:00',
    endTime: '18:00',
    location: 'Lecture Hall B, Building C',
    organizer: 'Student Development Center',
    capacity: 80,
    registeredCount: 72,
    registrationDeadline: '2026-02-23',
    category: 'workshop',
    tags: ['Skills', 'Speaking', 'Development'],
    coinReward: 80,
    status: 'open',
  },
];

// Registrations
export const mockRegistrations: Registration[] = [
  {
    id: 'reg-1',
    eventId: 'event-2',
    studentId: 'student-1',
    status: 'registered',
    registeredAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'reg-2',
    eventId: 'event-past-1',
    studentId: 'student-1',
    status: 'attended',
    registeredAt: '2026-01-10T10:00:00Z',
    attendedAt: '2026-01-15T14:00:00Z',
    coinsEarned: 100,
  },
  {
    id: 'reg-3',
    eventId: 'event-past-2',
    studentId: 'student-1',
    status: 'attended',
    registeredAt: '2026-01-20T10:00:00Z',
    attendedAt: '2026-01-25T10:00:00Z',
    coinsEarned: 75,
  },
];

// Leaderboard
export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, previousRank: 1, student: { id: 's1', name: 'Sarah Chen', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop', faculty: 'Engineering' }, coins: 4850, eventsAttended: 28 },
  { rank: 2, previousRank: 3, student: { id: 's2', name: 'Michael Brown', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop', faculty: 'Business' }, coins: 4200, eventsAttended: 25 },
  { rank: 3, previousRank: 2, student: { id: 's3', name: 'Emily Davis', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop', faculty: 'Arts' }, coins: 4100, eventsAttended: 24 },
  { rank: 4, previousRank: 4, student: { id: 's4', name: 'James Wilson', faculty: 'Sciences' }, coins: 3850, eventsAttended: 22 },
  { rank: 5, previousRank: 7, student: { id: 's5', name: 'Lisa Anderson', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop', faculty: 'Medicine' }, coins: 3600, eventsAttended: 21 },
  { rank: 6, previousRank: 5, student: { id: 's6', name: 'David Martinez', faculty: 'Law' }, coins: 3450, eventsAttended: 20 },
  { rank: 7, previousRank: 9, student: { id: 'student-1', name: 'Alex Johnson', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop', faculty: 'Computer Science' }, coins: 2450, eventsAttended: 15 },
  { rank: 8, previousRank: 6, student: { id: 's8', name: 'Jessica Taylor', faculty: 'Architecture' }, coins: 2400, eventsAttended: 14 },
  { rank: 9, previousRank: 10, student: { id: 's9', name: 'Robert Garcia', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop', faculty: 'Engineering' }, coins: 2350, eventsAttended: 14 },
  { rank: 10, previousRank: 8, student: { id: 's10', name: 'Amanda Lewis', faculty: 'Business' }, coins: 2300, eventsAttended: 13 },
  { rank: 11, previousRank: 11, student: { id: 's11', name: 'Daniel Kim', faculty: 'Sciences' }, coins: 2100, eventsAttended: 12 },
  { rank: 12, previousRank: 14, student: { id: 's12', name: 'Olivia White', faculty: 'Arts' }, coins: 2050, eventsAttended: 12 },
  { rank: 13, previousRank: 12, student: { id: 's13', name: 'William Harris', faculty: 'Medicine' }, coins: 2000, eventsAttended: 11 },
  { rank: 14, previousRank: 13, student: { id: 's14', name: 'Sophia Clark', faculty: 'Law' }, coins: 1950, eventsAttended: 11 },
  { rank: 15, previousRank: 16, student: { id: 's15', name: 'Christopher Lee', faculty: 'Engineering' }, coins: 1900, eventsAttended: 10 },
  { rank: 16, previousRank: 15, student: { id: 's16', name: 'Emma Robinson', faculty: 'Business' }, coins: 1850, eventsAttended: 10 },
  { rank: 17, previousRank: 18, student: { id: 's17', name: 'Andrew Walker', faculty: 'Sciences' }, coins: 1800, eventsAttended: 10 },
  { rank: 18, previousRank: 17, student: { id: 's18', name: 'Mia Hall', faculty: 'Arts' }, coins: 1750, eventsAttended: 9 },
  { rank: 19, previousRank: 20, student: { id: 's19', name: 'Joshua Allen', faculty: 'Computer Science' }, coins: 1700, eventsAttended: 9 },
  { rank: 20, previousRank: 19, student: { id: 's20', name: 'Charlotte Young', faculty: 'Medicine' }, coins: 1650, eventsAttended: 8 },
];

// Shop Items
export const mockShopItems: ShopItem[] = [
  {
    id: 'shop-1',
    name: 'University Hoodie',
    description: 'Premium quality hoodie with embroidered university logo. Comfortable cotton blend fabric.',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=300&fit=crop',
    category: 'merch',
    coinCost: 500,
    stock: 25,
    isAvailable: true,
  },
  {
    id: 'shop-2',
    name: 'Library Priority Access',
    description: 'Get priority access to study rooms and quiet zones during exam periods for one semester.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
    category: 'privileges',
    coinCost: 300,
    stock: 10,
    isAvailable: true,
  },
  {
    id: 'shop-3',
    name: 'Coffee Shop Voucher',
    description: '$10 voucher for the campus coffee shop. Valid for all drinks and snacks.',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop',
    category: 'services',
    coinCost: 100,
    stock: 50,
    isAvailable: true,
  },
  {
    id: 'shop-4',
    name: 'University T-Shirt',
    description: 'Classic university t-shirt in various colors. 100% cotton.',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop',
    category: 'merch',
    coinCost: 250,
    stock: 40,
    isAvailable: true,
  },
  {
    id: 'shop-5',
    name: 'Gym Access Pass',
    description: 'One month unlimited access to the university gym and fitness center.',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
    category: 'privileges',
    coinCost: 400,
    stock: 20,
    isAvailable: true,
  },
  {
    id: 'shop-6',
    name: 'Bookstore Discount Card',
    description: '15% discount on all purchases at the university bookstore for one semester.',
    image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400&h=300&fit=crop',
    category: 'services',
    coinCost: 350,
    stock: 0,
    isAvailable: false,
  },
  {
    id: 'shop-7',
    name: 'University Cap',
    description: 'Adjustable cap with embroidered university logo. One size fits all.',
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&h=300&fit=crop',
    category: 'merch',
    coinCost: 150,
    stock: 35,
    isAvailable: true,
  },
  {
    id: 'shop-8',
    name: 'Parking Priority',
    description: 'Priority parking spot near your faculty building for one month.',
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=400&h=300&fit=crop',
    category: 'privileges',
    coinCost: 600,
    stock: 5,
    isAvailable: true,
  },
];

// Transactions
export const mockTransactions: Transaction[] = [
  { id: 'tx-1', type: 'earned', amount: 100, description: 'Attended Tech Workshop', source: 'event_attendance', referenceId: 'event-past-1', createdAt: '2026-02-04T15:00:00Z' },
  { id: 'tx-2', type: 'spent', amount: 250, description: 'Redeemed University T-Shirt', source: 'shop_redemption', referenceId: 'shop-4', createdAt: '2026-02-03T10:30:00Z' },
  { id: 'tx-3', type: 'earned', amount: 75, description: 'Attended Cultural Night', source: 'event_attendance', referenceId: 'event-past-2', createdAt: '2026-02-01T22:00:00Z' },
  { id: 'tx-4', type: 'earned', amount: 50, description: 'Early Bird Badge Bonus', source: 'achievement', createdAt: '2026-01-28T09:00:00Z' },
  { id: 'tx-5', type: 'earned', amount: 200, description: 'Volunteer Event Participation', source: 'event_attendance', createdAt: '2026-01-25T14:00:00Z' },
  { id: 'tx-6', type: 'spent', amount: 100, description: 'Redeemed Coffee Voucher', source: 'shop_redemption', referenceId: 'shop-3', createdAt: '2026-01-22T11:00:00Z' },
  { id: 'tx-7', type: 'earned', amount: 150, description: 'Career Fair Attendance', source: 'event_attendance', createdAt: '2026-01-20T16:00:00Z' },
  { id: 'tx-8', type: 'earned', amount: 100, description: 'Welcome Bonus', source: 'bonus', createdAt: '2024-09-01T10:00:00Z' },
];

// Notifications
export const mockNotifications: Notification[] = [
  { id: 'notif-1', type: 'coins_received', title: 'Coins Earned!', message: 'You earned 100 coins for attending the Tech Workshop.', isRead: false, createdAt: '2026-02-04T15:00:00Z', referenceId: 'event-past-1' },
  { id: 'notif-2', type: 'event_reminder', title: 'Event Tomorrow', message: 'Reminder: Career Fair 2026 is happening tomorrow at 10:00 AM.', isRead: false, createdAt: '2026-02-04T09:00:00Z', referenceId: 'event-2' },
  { id: 'notif-3', type: 'redeem_status', title: 'Item Ready for Pickup', message: 'Your University T-Shirt is ready for pickup at the Student Center.', isRead: true, createdAt: '2026-02-03T14:00:00Z', referenceId: 'shop-4' },
  { id: 'notif-4', type: 'announcement', title: 'New Announcement', message: 'Spring Semester Registration is now open. Register before Feb 15th.', isRead: true, createdAt: '2026-02-03T08:00:00Z', referenceId: 'ann-1' },
  { id: 'notif-5', type: 'achievement', title: 'Badge Earned!', message: 'Congratulations! You earned the Social Butterfly badge.', isRead: true, createdAt: '2026-01-20T14:00:00Z' },
  { id: 'notif-6', type: 'registration_update', title: 'Registration Confirmed', message: 'Your registration for Career Fair 2026 has been confirmed.', isRead: true, createdAt: '2026-02-01T10:00:00Z', referenceId: 'event-2' },
];
